remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
- jekyll-katex
logo: /asset/dennisAndBird.png
title: DE的大鞭炮
description: 哈囉，歡迎來到 Dennis Black 的個人網站，這個網站主要是我的筆記。
show_downloads: false

